select Prospect_ID
, Country
, Specialization
, City
, How_did_you_hear_about_X_Education
, What_matters_most_to_you_in_choosing_a_course
, What_is_your_current_occupation
, Through_Recommendations
, Receive_More_Updates_About_Our_Courses
, Search
, Magazine
, Newspaper_Article
, X_Education_Forums
, Newspaper
, Digital_Advertisement
, I_agree_to_pay_the_amount_through_cheque
, a_free_copy_of_Mastering_The_Interview
, Update_me_on_Supply_Chain_Content
, Get_updates_on_DM_Content
from `continual-dev.dbt_brendan.lead_scoring`